import mongoose, { Schema } from "mongoose";

const plantSchema = new Schema({
    name:[{
      commonName:{
        type:String,
        require:true,
        trim:true
      },  
      scientificName:{
        type:String,
        require:true,
        trim:true
      }  
    }],
    seller:{
        type:String,
        require:true,
        trim
    },
    description:{
        type:String,
        require:true
    },
    price:{
        type:Number,
        require:true,
        min:0
    },
    discount:{
        type:Number,
        default:0,
        min:0,
        max:99
    },
    category:{
        type:String,
        require:true,
        trim:true
    },
    stock:{
        type:Number,
        require:true,
        default:0,
        min:0
    },
    sku:{
        type:String,
        unique:true,
        require:true,
        trim:true
    },
    images:[{
        url
    }],
    plantDetail:{
        plantType:{
            type:String,
            require:true,
            trim:true
        },
        lightNeed:{
            type:String,
            require:true
        },
        waterNeed:{
            type:String,
            require:true
        },
        growthZone:{
            type:String,
            require:true
        },
        detailDescription:{
            type:String,
            require:true
        },
        maintenanceGuide:{
            type:String
        },
        season:{
            type:String,
            require:true
        },
        tags:[String]
    },
    reviews:[
        {
            user:{
                type:Schema.Types.ObjectId,
                ref:"Order",
                require:true
            },
            rating:{
                type:Number,
                min:1,
                max:5,
                require:true
            },
            comment:{
                type:String,
            },
            uploadImage:[
                
            ],
            isListed:{
                type:Boolean,
                default:false
            }
            
        },
        {
            timestamps:true
        }
    ]
 },
 {
    timestamps:true
});

export const Plant = mongoose.model("Plant", plantSchema)
